name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args:  --verbose --release

    - name: Run list files
      run: ls target/release

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
          name: output
          path: |
            target/release
            !target/release/.fingerprint/**
            !target/release/build/**
            !target/release/deps/**
