name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run list files
      run: ls target
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
          name: output
          path: |
            debug
            !debug/.fingerprint/**
            !debug/build/**
            !debug/deps/**
